# Workflow derived from https://www.python-engineer.com/posts/run-python-github-actions/
name: Run SA Nowcasting Model

on:
  # Runs whenever we have a new vintage https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed
  schedule:
    - cron: '15 1 * * 5'

  # Optional Workflow Dispatch Trigger
  workflow_dispatch:

jobs:
  RunSANowcast: 
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas statsmodels openpyxl

      - name: execute py script
        run: python code/nowcast_auto_econdata.py

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4